//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADGV.Localization
{


    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ADGVStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ADGVStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADGV.Localization.ADGVStrings", typeof(ADGVStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string cancelbutton_text {
            get {
                return ResourceManager.GetString("cancelbutton_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear filter.
        /// </summary>
        internal static string cancelfiltermenuitem_text {
            get {
                return ResourceManager.GetString("cancelfiltermenuitem_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel sort.
        /// </summary>
        internal static string cancelsortmenuitem_text {
            get {
                return ResourceManager.GetString("cancelsortmenuitem_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на h.
        /// </summary>
        internal static string checknodetree_hour {
            get {
                return ResourceManager.GetString("checknodetree_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ms.
        /// </summary>
        internal static string checknodetree_millisecond {
            get {
                return ResourceManager.GetString("checknodetree_millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на m.
        /// </summary>
        internal static string checknodetree_minute {
            get {
                return ResourceManager.GetString("checknodetree_minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на s.
        /// </summary>
        internal static string checknodetree_second {
            get {
                return ResourceManager.GetString("checknodetree_second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date filter.
        /// </summary>
        internal static string filtersmenuitem_text_datetime {
            get {
                return ResourceManager.GetString("filtersmenuitem_text_datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number filter.
        /// </summary>
        internal static string filtersmenuitem_text_numeric {
            get {
                return ResourceManager.GetString("filtersmenuitem_text_numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text Filter.
        /// </summary>
        internal static string filtersmenuitem_text_text {
            get {
                return ResourceManager.GetString("filtersmenuitem_text_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на January.
        /// </summary>
        internal static string month1 {
            get {
                return ResourceManager.GetString("month1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на October.
        /// </summary>
        internal static string month10 {
            get {
                return ResourceManager.GetString("month10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на November.
        /// </summary>
        internal static string month11 {
            get {
                return ResourceManager.GetString("month11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на December.
        /// </summary>
        internal static string month12 {
            get {
                return ResourceManager.GetString("month12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на February.
        /// </summary>
        internal static string month2 {
            get {
                return ResourceManager.GetString("month2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на March.
        /// </summary>
        internal static string month3 {
            get {
                return ResourceManager.GetString("month3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на April.
        /// </summary>
        internal static string month4 {
            get {
                return ResourceManager.GetString("month4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на May.
        /// </summary>
        internal static string month5 {
            get {
                return ResourceManager.GetString("month5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на June.
        /// </summary>
        internal static string month6 {
            get {
                return ResourceManager.GetString("month6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на July.
        /// </summary>
        internal static string month7 {
            get {
                return ResourceManager.GetString("month7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на August.
        /// </summary>
        internal static string month8 {
            get {
                return ResourceManager.GetString("month8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на September.
        /// </summary>
        internal static string month9 {
            get {
                return ResourceManager.GetString("month9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        internal static string okbutton_text {
            get {
                return ResourceManager.GetString("okbutton_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на and.
        /// </summary>
        internal static string setfilterform_andlabel_text {
            get {
                return ResourceManager.GetString("setfilterform_andlabel_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string setfilterform_cancelbutton_text {
            get {
                return ResourceManager.GetString("setfilterform_cancelbutton_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show rows where value.
        /// </summary>
        internal static string setfilterform_columnnamelabel_text {
            get {
                return ResourceManager.GetString("setfilterform_columnnamelabel_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid value.
        /// </summary>
        internal static string setfilterform_errorprovider_value {
            get {
                return ResourceManager.GetString("setfilterform_errorprovider_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на later than.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_after {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на earlier than.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_before {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на begins with.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_begins {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_begins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на between.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_between {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на contains.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_contain {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_contain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ends with.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_ends {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_ends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на equals.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_equal {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на greater than or equal to.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_lagerequals {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_lagerequals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на greater than.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_larger {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_larger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на less than.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_less {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на less than or equal to.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_lessequals {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_lessequals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на does not begin with.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_nobegins {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_nobegins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на does not contain.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_nocontain {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_nocontain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на does not end with.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_noends {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_noends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на does not equal.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_notequal {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_notequal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        internal static string setfilterform_okbutton_text {
            get {
                return ResourceManager.GetString("setfilterform_okbutton_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set filter.
        /// </summary>
        internal static string setfilterform_text {
            get {
                return ResourceManager.GetString("setfilterform_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на and.
        /// </summary>
        internal static string setfilterform_viewfilterstring_and {
            get {
                return ResourceManager.GetString("setfilterform_viewfilterstring_and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show rows where value.
        /// </summary>
        internal static string setfilterform_viewfilterstring_mustbe {
            get {
                return ResourceManager.GetString("setfilterform_viewfilterstring_mustbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom.
        /// </summary>
        internal static string setupfiltermenuitem_text {
            get {
                return ResourceManager.GetString("setupfiltermenuitem_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort by False/True.
        /// </summary>
        internal static string sortascmenuitem_text_boolean {
            get {
                return ResourceManager.GetString("sortascmenuitem_text_boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort oldest to newest.
        /// </summary>
        internal static string sortascmenuitem_text_datetime {
            get {
                return ResourceManager.GetString("sortascmenuitem_text_datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort smallest to largest.
        /// </summary>
        internal static string sortascmenuitem_text_numeric {
            get {
                return ResourceManager.GetString("sortascmenuitem_text_numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort А to Z.
        /// </summary>
        internal static string sortascmenuitem_text_text {
            get {
                return ResourceManager.GetString("sortascmenuitem_text_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort Z to A.
        /// </summary>
        internal static string sortdescmenuitem_text {
            get {
                return ResourceManager.GetString("sortdescmenuitem_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort by True/False.
        /// </summary>
        internal static string sortdescmenuitem_text_boolean {
            get {
                return ResourceManager.GetString("sortdescmenuitem_text_boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort newest to oldest.
        /// </summary>
        internal static string sortdescmenuitem_text_datetime {
            get {
                return ResourceManager.GetString("sortdescmenuitem_text_datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort largest to smallest.
        /// </summary>
        internal static string sortdescmenuitem_text_numeric {
            get {
                return ResourceManager.GetString("sortdescmenuitem_text_numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Select All).
        /// </summary>
        internal static string tripletreenode_allnode_text {
            get {
                return ResourceManager.GetString("tripletreenode_allnode_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на False.
        /// </summary>
        internal static string tripletreenode_boolean_false {
            get {
                return ResourceManager.GetString("tripletreenode_boolean_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на True.
        /// </summary>
        internal static string tripletreenode_boolean_true {
            get {
                return ResourceManager.GetString("tripletreenode_boolean_true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Blanks).
        /// </summary>
        internal static string tripletreenode_nullnode_text {
            get {
                return ResourceManager.GetString("tripletreenode_nullnode_text", resourceCulture);
            }
        }
    }
}
